services:
  db:
    image: postgres:18-alpine
    container_name: alumni-db
    environment:
      POSTGRES_DB: alumni_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: ./backend
    container_name: alumni-api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/alumni_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  web:
    build: ./frontend
    container_name: alumni-frontend
    ports:
      - "80:80"
    depends_on:
      - api

volumes:
  postgres_data:
