# FROM maven:3.9-eclipse-temurin-25
# WORKDIR /app
# COPY pom.xml .
# RUN mvn dependency:go-offline
# COPY src ./src
# # Le mode run permet au plugin spring-boot de détecter les changements
# CMD ["mvn", "spring-boot:run"]


# backend/Dockerfile.dev
FROM maven:3.9-eclipse-temurin-25
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline
COPY src ./src
EXPOSE 8080
CMD ["mvn", "spring-boot:run"]