spring.application.name=alumni-backend
spring.datasource.driver-class-name=org.postgresql.Driver
spring.profiles.default=dev

jwt.expiration=${JWT_EXPIRATION_MS:900000}
jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION_MS:2592000000}
